### ISSUE TITLE
upgrade to 1.5 causes NPE on PR merge attempt

### ISSUE THREAD

**Issue by spoage** [monitorjbl/pr-harmony#12]
**Stash version:** 3.8.0
**When it occurs:** when a user goes to merge a PR
**Reported workaround:** some users reported that setting an empty value in the settings to zero eliminated the error, but we did not get that report until after we had already rolled back to 1.4, so we could not test.

**Stack trace:**

```
2015-08-04 12:53:05,042 WARN  [http-nio-127.0.0.1-7990-exec-1442] USERNAME @30IR7Yx773x27609499x6 pryjib IP_ADDRESS,127.0.0.1 "GET /rest/api/latest/projects/~USERNAME/repos/migration-sync/pull-requests/1/merge HTTP/1.1" c.a.s.i.p.DefaultMergeRequestCheckService Merge request check com.monitorjbl.plugins.pr-harmony:mergeCheck of type com.monitorjbl.plugins.MergeBlocker failed.
java.lang.NullPointerException: null
        at com.monitorjbl.plugins.PullRequestApproval.isPullRequestApproved(PullRequestApproval.java:27) ~[na:na]
        at com.monitorjbl.plugins.MergeBlocker.check(MergeBlocker.java:36) ~[na:na]
com.atlassian.stash.internal.pull.DefaultMergeRequestCheckService.doCheck(DefaultMergeRequestCheckService.java:73) [stash-service-impl-3.8.0.jar:na]
        at com.atlassian.stash.internal.pull.DefaultMergeRequestCheckService.checkMergeability(DefaultMergeRequestCheckService.java:57) [stash-service-impl-3.8.0.jar:na]
        at com.atlassian.stash.internal.pull.DefaultPullRequestService.canMerge(DefaultPullRequestService.java:312) [stash-service-impl-3.8.0.jar:na]
        at com.atlassian.stash.internal.rest.pull.PullRequestResource.canMerge(PullRequestResource.java:396) [stash-rest-3.8.0.jar:na]
        at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:25) [applinks-plugin-4.3.5_1425989430000.jar:na]
        at com.atlassian.stash.internal.spring.security.StashAuthenticationFilter.doFilter(StashAuthenticationFilter.java:83) [StashAuthenticationFilter.class:na]
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doInsideSpringSecurityChain(BeforeLoginPluginAuthenticationFilter.java:111) [BeforeLoginPluginAuthenticationFilter.class:na]
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:77) [BeforeLoginPluginAuthenticationFilter.class:na]
        at com.atlassian.security.auth.trustedapps.filter.TrustedApplicationsFilter.doFilter(TrustedApplicationsFilter.java:100) [atlassian-trusted-apps-core-3.0.8.jar:na]
        at com.atlassian.oauth.serviceprovider.internal.servlet.OAuthFilter.doFilter(OAuthFilter.java:79) [atlassian-oauth-service-provider-plugin-1.9.10_1421720264000.jar:na]
        at com.atlassian.analytics.client.filter.DefaultAnalyticsFilter.doFilter(DefaultAnalyticsFilter.java:32) [analytics-client-3.65_1427099260000.jar:na]
        at com.atlassian.analytics.client.filter.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:32) [analytics-client-3.65_1427099260000.jar:na]
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doBeforeBeforeLoginFilters(BeforeLoginPluginAuthenticationFilter.java:89) [BeforeLoginPluginAuthenticationFilter.class:na]
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:75) [BeforeLoginPluginAuthenticationFilter.class:na]
        at com.atlassian.stash.internal.request.DefaultRequestManager.doAsRequest(DefaultRequestManager.java:85) [stash-service-impl-3.8.0.jar:na]
        at com.atlassian.stash.internal.hazelcast.ConfigurableWebFilter.doFilter(ConfigurableWebFilter.java:38) [ConfigurableWebFilter.class:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
        ... 281 frames trimmed
```

**Comment by monitorjbl** [comment]
Ah, autounboxing strikes again! Just need a null guard there. I'll get that added right away. 

By the way, your version of Stash is really old. I'm surprised the plugin works at all for you!

**Comment by spoage** [comment]
Glad you found it quickly. :) On unrelated and completely unreasonably defensive note: it's not _that_ old... 3.8 released back in mid-May. That's less than 3 months. :P

Anyway, thanks for the quick response, and appreciate the good work - it's a great plugin. :)

**Comment by monitorjbl** [comment]
Oh, your original post said 1.8.0. 3.8 is a lot more reasonable!

**Comment by spoage** [comment]
I just realized that as you responded. Whoops! Now I feel silly, haha. Edited. :)
