### ISSUE TITLE
Configuration fails to save w/ error in log file

### ISSUE THREAD

**Issue by jbcraig** [monitorjbl/pr-harmony#26]
BitBucket v4.1.0
PR Harmon v2.0

Unless I fill in something for every config box the save button fails (no UI notification/response) with a log message like:

2015-11-13 11:08:15,914 ERROR [http-nio-7990-exec-8] jcraig @1RD8OKHx668x10785x0 ld8o0z X.X.X.X "PUT /rest/pr-harmony/1.0/config/TJ/repo01 HTTP/1.1" c.a.p.r.c.e.j.ThrowableExceptionMapper Uncaught exception thrown by REST service: cannot be blank
java.lang.IllegalArgumentException: cannot be blank
    at com.atlassian.bitbucket.util.CustomPreconditions.checkRequiredString(CustomPreconditions.java:22) ~[bitbucket-api-4.1.0.jar:na]
    at com.atlassian.stash.internal.plugin.PluginSetting.<init>(PluginSetting.java:56) ~[bitbucket-model-4.1.0.jar:na]
    at com.atlassian.stash.internal.plugin.PluginSetting.<init>(PluginSetting.java:24) ~[bitbucket-model-4.1.0.jar:na]
    at com.atlassian.stash.internal.plugin.PluginSetting$Builder.build(PluginSetting.java:95) ~[bitbucket-model-4.1.0.jar:na]
    at com.atlassian.stash.internal.plugin.HibernatePluginSettingDao.put(HibernatePluginSettingDao.java:39) ~[bitbucket-dao-impl-4.1.0.jar:na]
    at com.atlassian.stash.internal.plugin.DefaultPluginSettings.putActual(DefaultPluginSettings.java:55) ~[bitbucket-platform-4.1.0.jar:na]
    at com.atlassian.sal.core.pluginsettings.AbstractStringPluginSettings.put(AbstractStringPluginSettings.java:75) ~[sal-core-3.0.5.jar:na]
    at com.atlassian.stash.internal.plugin.DefaultPluginSettings.put(DefaultPluginSettings.java:34) ~[bitbucket-platform-4.1.0.jar:na]
    at com.atlassian.stash.internal.plugin.ContextClassLoaderSettingInvocationHandler.invoke(ContextClassLoaderSettingInvocationHandler.java:24) ~[bitbucket-platform-4.1.0.jar:na]
    at com.monitorjbl.plugins.config.ConfigDao.writeConfig(ConfigDao.java:79) ~[plugin_1983220253859657040_pr-harmony-2.0_1447424352000.jar:na]
    at com.monitorjbl.plugins.config.ConfigDao.setConfigForRepo(ConfigDao.java:43) ~[plugin_1983220253859657040_pr-harmony-2.0_1447424352000.jar:na]
    at com.monitorjbl.plugins.config.ConfigResource.setRepoConfig(ConfigResource.java:38) ~[plugin_1983220253859657040_pr-harmony-2.0_1447424352000.jar:na]
    at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:26) [applinks-plugin-5.0.1_1446455420000.jar:na]
    at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:26) [applinks-plugin-5.0.1_1446455420000.jar:na]
    at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:26) [applinks-plugin-5.0.1_1446455420000.jar:na]
    at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:26) [applinks-plugin-5.0.1_1446455420000.jar:na]
    at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:26) [applinks-plugin-5.0.1_1446455420000.jar:na]
    at com.atlassian.stash.internal.spring.security.StashAuthenticationFilter.doFilter(StashAuthenticationFilter.java:88) [StashAuthenticationFilter.class:na]
    at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doInsideSpringSecurityChain(BeforeLoginPluginAuthenticationFilter.java:109) [BeforeLoginPluginAuthenticationFilter.class:na]
    at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:75) [BeforeLoginPluginAuthenticationFilter.class:na]
    at com.atlassian.security.auth.trustedapps.filter.TrustedApplicationsFilter.doFilter(TrustedApplicationsFilter.java:94) [atlassian-trusted-apps-core-4.2.0.jar:na]
    at com.atlassian.oauth.serviceprovider.internal.servlet.OAuthFilter.doFilter(OAuthFilter.java:67) [atlassian-oauth-service-provider-plugin-2.0.3_1446455420000.jar:na]
    at com.atlassian.analytics.client.filter.DefaultAnalyticsFilter.doFilter(DefaultAnalyticsFilter.java:36) [analytics-client-4.3.2_1446455420000.jar:na]
    at com.atlassian.analytics.client.filter.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:32) [analytics-client-4.3.2_1446455420000.jar:na]
    at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doBeforeBeforeLoginFilters(BeforeLoginPluginAuthenticationFilter.java:87) [BeforeLoginPluginAuthenticationFilter.class:na]
    at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:73) [BeforeLoginPluginAuthenticationFilter.class:na]
    at com.atlassian.stash.internal.request.DefaultRequestManager.doAsRequest(DefaultRequestManager.java:85) ~[bitbucket-service-impl-4.1.0.jar:na]
    at com.atlassian.stash.internal.hazelcast.ConfigurableWebFilter.doFilter(ConfigurableWebFilter.java:38) ~[ConfigurableWebFilter.class:na]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_60]
    at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_60]
    ... 253 frames trimmed

I also receive this error if I blank all the fields and submit.  Leaving no way to clear configuration settings.

**Comment by jbcraig** [comment]
First, thank you for sharing your work so others may benefit.  I'll preface my comments by first saying, " I'm not a java programmer",  so take whatever I say with a grain of salt.  To best of my google abilities it looks like atlassian won't let you store an empty string.  That means one must use the pluginSettings.remove, rather than store an empty string.  I am surprised that I'm the only one having this problem which makes me suspect it's me.  Unfortunately, I have been unable to detect my mistake.  Any help or guidance would be appreciated.

**Comment by monitorjbl** [comment]
That is...quite odd. The plugin's `Config` object sets default, non-null (but empty) values for all fields. The only way to set a field to null is to explicitly set it as such in the JSON that gets sent to the server. The UI shouldn't do that; at best the field will be undefined which is the same as the field not existing.

This error is definitely not your doing, I think Atlassian changed something internal in the latest version of Bitbucket. I'd only tested up to 4.0 for the latest release of the plugin. Checking it out locally now...

**Comment by jbcraig** [comment]
I found stuff on various sites that leads me to believe that if its "null" then the key will be removed from the settings and a empty string isn't legal for array and map types.

Having a method of clearing/removing the settings would be nice.  In my testing I noticed that if I delete the repo/project and then recreate with the same key the old settings remain.  This could be surprising for some if they turnover projects and re-use the short names.

**Comment by monitorjbl** [comment]
Just stepped through the code, the field is definitely not null and neither is what's going into the `PluginSettings` object. It's sending in a blank string which appears to now be against the rules...in retrospect, the exception definitely said that but I didn't notice:

```
java.lang.IllegalArgumentException: cannot be blank
```

[The documentation](https://developer.atlassian.com/static/javadoc/sal/latest/reference/com/atlassian/sal/api/pluginsettings/PluginSettings.html) doesn't mention this restriction, but I suppose that wouldn't be unprecedented during times of great change. The whole Stash -> Bitbucket migration has been more than a little painful :(

**Comment by monitorjbl** [comment]
And to be clear, the intended functionality is that if you clear a field in the UI, it is cleared in the backend as well.

**Comment by monitorjbl** [comment]
I've reconfirmed that this issue does _not_ occur in 4.0. I've got a [question open to Atlassian](https://answers.atlassian.com/questions/32510704/should-pluginsettings.put-accept-blank-strings) right now. If this is an intentional change on their part, I'll redo this logic to make sure that blank values call `remove()`.

**Comment by jbcraig** [comment]
I don't know if this helps but following that api doc it says a "null" will remove, that may be easier to code (https://developer.atlassian.com/static/javadoc/sal/2.3/reference/com/atlassian/sal/api/pluginsettings/PluginSettings.html#put(java.lang.String, java.lang.Object)

This is where I came across the empty string issues.  You'll likely be better able to know if this applies to your code (https://ecosystem.atlassian.net/browse/SAL-311)

**Comment by jbcraig** [comment]
I'll also mention that there is one field that may be blanked and that is the number of required reviewers.

**Comment by monitorjbl** [comment]
Atlassian confirmed that this was unintended and will be reverted in a future version. I'll update the issue when they give me a target fix version.

**Comment by jbcraig** [comment]
Thank you for your efforts.  I have a simple fix that resolves this issue and should maintain compatibility backwards/forwards.  If you are interested I can send you either a patch file or a pull request.

**Comment by monitorjbl** [comment]
Absolutely, feel free to open a PR!
